"""initial

Revision ID: cfeee9cdc41e
Revises: fc3bd8f713f2
Create Date: 2024-04-22 20:45:16.757334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfeee9cdc41e'
down_revision: Union[str, None] = 'fc3bd8f713f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_logs_id', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rtsp_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_logs_pkey')
    )
    op.create_index('ix_api_logs_id', 'api_logs', ['id'], unique=False)
    # ### end Alembic commands ###
